### ISSUE TITLE
Support to MessageConverter

### ISSUE THREAD

**Issue by ignacio83** [netshoes/spring-cloud-sleuth-amqp#15]
The current implementation does not allow the use of [`Jackson2JsonMessageConverter`](https://docs.spring.io/spring-amqp/docs/2.0.1.RELEASE/reference/html/_reference.html#json-message-converter) in combination with `@RabbitHandler` (Issue #13)

e.g. 

```
@Component
@RabbitListener(bindings = {
		@QueueBinding(
				value = @Queue(value = "QUEUE", autoDelete = "true"), 
				exchange = @Exchange(value = "EXCHANGE", autoDelete = "true", type = "direct"), 
				key = "KEY")}
)
public class EventHandler {

	@RabbitHandler
	public void onEvent(MyEvent event) {
               // do something with event
	}

}
```

Methods annotated with `@RabbitHandler` are selected because of the converted payload, at this time there is no direct access to the message (and therefore to the span) anymore.

**Comment by ignacio83** [comment]
@imod says:

So far I have no idea how to fix the #15, what I did as a dirty workaround on for us, was this:

I created a wrapper to wrap the MessageConverter:
public class AmqpMessagingSpanSleuthExtractorMessageConverterWrapper implements MessageConverter {

	private static final Logger LOGGER = LoggerFactory.getLogger(AmqpMessagingSpanSleuthExtractorMessageConverterWrapper.class);

	private final MessageConverter wrappedConverter;
	private final AmqpMessagingSpanManager spanManager;

	public AmqpMessagingSpanSleuthExtractorMessageConverterWrapper(MessageConverter wrappedConverter, AmqpMessagingSpanManager spanManager) {
		this.wrappedConverter = wrappedConverter;
		this.spanManager = spanManager;
	}

	@Override
	public Message toMessage(Object object, MessageProperties messageProperties) throws MessageConversionException {
		return wrappedConverter.toMessage(object, messageProperties);
	}

	@Override
	public Object fromMessage(Message message) throws MessageConversionException {
		try {
			spanManager.beforeHandle(message, new String[] {});
		} catch (Exception e) {
			LOGGER.error("failed to handle sleuth 'span' before converting message!", e);
		}
		return wrappedConverter.fromMessage(message);
	}

}
I configured the SimpleRabbitListenerContainerFactory to use the wrapper instead of the Jackson2JsonMessageConverter directly...
	@Bean
	public SimpleRabbitListenerContainerFactory rabbitListenerContainerFactory(ConnectionFactory connectionFactory, ObjectMapper mapper, AmqpMessagingSpanManager spanManager) {
		SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
		factory.setConnectionFactory(connectionFactory);
		factory.setMessageConverter(new AmqpMessagingSpanSleuthExtractorMessageConverterWrapper(jacksonConverter(mapper), spanManager));
		return factory;
	}

	private Jackson2JsonMessageConverter jacksonConverter(ObjectMapper mapper) {
		return new Jackson2JsonMessageConverter(mapper);
	}
Additional note about this PR: I'm not sure why com.netshoes.springframework.cloud.sleuth.instrument.amqp.RabbitListenerAspect#getQueueNames actually exists, because com.netshoes.springframework.cloud.sleuth.instrument.amqp.DefaultAmqpMessagingSpanManager#beforeHandle does not do anything with the passed queueNames - it seems this parameter is only there for testing purposes. But I think for this the call is far to expensive and should be removed in RabbitListenerAspect and in the new RabbitHandlerAspect of this PR.

**Comment by ignacio83** [comment]
I think is a good idea create 'AmqpMessagingSpanSleuthExtractorMessageConverterWrapper''.
But is really dirty call setMessageConverter informing it.

What you think about instrument the method setMessageConverter and inside aspect create a instance of 'AmqpMessagingSpanSleuthExtractorMessageConverterWrapper'? 

Instead call 'ProceedingJoinPoint.proceed', you can create create your wrapper, get the target from 'ProceedingJoinPoint' and call 'setMessageConverter'.

There is as a similar flow in code of class 'AmqpTemplateAspect' in lines 118 and 125. In this code I was change the call of original method who informed a 'PostProcessor' and wrap it in a 'CompositeMessagePostProcessor'.

**Comment by ignacio83** [comment]
@imod My ideia above will not working, because is not possible use @AspectJ in class who is not a Spring Bean. I will think about.

**Comment by ignacio83** [comment]
@imod It is really necessary call `beforeHandle` when we changed the `MessageConverter`?
The implementation who you did in issue #13 is not resolved this problem?

**Comment by imod** [comment]
@ignacio83 I just tested again, unfortunate it does not work without the `AmqpMessagingSpanSleuthExtractorMessageConverterWrapper` :(

**Comment by imod** [comment]
@ignacio83 I did quite a bit of testing, but I was not able to find a Pointcut definition that would work.
Here is the full Stack of the call:

```
Thread [SimpleAsyncTaskExecutor-1] (Suspended (breakpoint at line 39 in AmqpMessagingSpanSleuthExtractorMessageConverterWrapper))	
	AmqpMessagingSpanSleuthExtractorMessageConverterWrapper.fromMessage(Message) line: 39	
	MessagingMessageListenerAdapter(AbstractAdaptableMessageListener).extractMessage(Message) line: 236	
	MessagingMessageListenerAdapter$MessagingMessageConverterAdapter.extractPayload(Message) line: 216	
	MessagingMessageListenerAdapter$MessagingMessageConverterAdapter(MessagingMessageConverter).fromMessage(Message) line: 118	
	MessagingMessageListenerAdapter.toMessagingMessage(Message) line: 116	
	MessagingMessageListenerAdapter.onMessage(Message, Channel) line: 102	
	SimpleMessageListenerContainer(AbstractMessageListenerContainer).doInvokeListener(ChannelAwareMessageListener, Channel, Message) line: 822	
	SimpleMessageListenerContainer(AbstractMessageListenerContainer).invokeListener(Channel, Message) line: 745	
	SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer, Channel, Message) line: 97	
	SimpleMessageListenerContainer$1.invokeListener(Channel, Message) line: 189	
	SimpleMessageListenerContainer.invokeListener(Channel, Message) line: 1276	
	SimpleMessageListenerContainer(AbstractMessageListenerContainer).executeListener(Channel, Message) line: 726	
	SimpleMessageListenerContainer.doReceiveAndExecute(BlockingQueueConsumer) line: 1219	
	SimpleMessageListenerContainer.receiveAndExecute(BlockingQueueConsumer) line: 1189	
	SimpleMessageListenerContainer.access$1500(SimpleMessageListenerContainer, BlockingQueueConsumer) line: 97	
	SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run() line: 1421	
	Thread.run() line: 745	
```

**Comment by ignacio83** [comment]
@imod In you tests, how are you posting messages to be consuming with RabbitHandler?
Sorry, but I can't simulate this problem yet.
I created a branch `feature/jackson_support_with_rabbit_handler` to try simulate this problem. Could u check class `RabbitHandlerAspectWithJacksonConverterTest`?

**Comment by imod** [comment]
@ignacio83 I created a simple demo project showing the issue: https://github.com/imod/spring-boot-sleuth-rabbit-demo/tree/master

**Comment by javajack** [comment]
+1 I am facing this issue too.

When we annotate the RabbitListener with a specific object type. instead of Message this issue arises.

I am joining this thread to get updates on this issue.

BTW the library is very useful overall. Thanks a lot.

**Comment by ignacio83** [comment]
I got a solution making a instrumentation in MessageConverter.fromMessage(). At next week I will make more tests and release a new version.

You could check in branch feature/issue_15

**Comment by ignacio83** [comment]
There are a branch of starter too:
https://github.com/netshoes/spring-cloud-sleuth-amqp-starter/tree/feature/issue_15

**Comment by imod** [comment]
@ignacio83 thats good news - many thanks!

**Comment by ignacio83** [comment]
@imod Thanks by support
Version 0.9 released.

**Comment by imod** [comment]
you'r very welcome! - I'm happy I can remove my custom implementation :)

**Comment by javajack** [comment]
I am using custom wrapper as of now.
My use case is based on @RabbitListener annottaion at the method level instead of @RabbitHandler

Is it ok to upgrade to new release ? Or shall I continue using the wrapper ?

**Comment by imod** [comment]
@javajack you should be fine to upgrade. You should also be able to remove the wrapper, but make sure four `MessageConverter` is exposed as `@Bean` otherwise the AOP Aspect will not kick in.
