### ISSUE TITLE
Provide an Example Project for MessageConverter + RabbitListener instrumentation

### ISSUE THREAD

**Issue by Laures** [netshoes/spring-cloud-sleuth-amqp#18]
I'm currently trying to use this library to instrument my existing AMQP event system.

While the AmqpTemplate instrumentation worked without a problem my attempts to trace message consumers fail. The provided messageconverter-Aspect will only detach spans instead of closing them, so they are not reported and the rabbitlistener-Aspect ignores listeners that use a converter.

I guess i'm missing something obvious here.

This is how my listeners look:
```
public class AccountEventListener {
    @RabbitListener(bindings = {
        @QueueBinding(
            value = @Queue(value = "queue1", durable = "true"),
            exchange = @Exchange(value = "exchange"), key = "pattern1")
    })
    public void event1(User user) {
    }

    @RabbitListener(bindings = {
        @QueueBinding(
            value = @Queue(value = "queue2", durable = "true"),
            exchange = @Exchange(value = "exchange"), key = "pattern2")
    })
    public void event2(Acquisition acquisition) {
    }
}
```
(listeners are grouped in classes based on context)

**Comment by ignacio83** [comment]
@Laures You are right, the class responsible to continueSpan in your case is MessageConverterAspect, because you are using a Pojo rather than receive a Message.

Why you need close the Span after receive message? 
This implementation is based in
`org.springframework.cloud.sleuth.instrument.messaging.TraceChannelInterceptor`, and in this implementation the span is not closed, only detached.

**Comment by Laures** [comment]
my main goal is to trace message consumption and connect it to the sender. since a span is only reported when it is closed, a child-Span, based on the Message-Span, needs to be closed.

Right now, there is a span for sending a message (reported by the origin server; `AmqpTemplateAspect`), its continuation for converting the message (not reported; `MessageConverterAspect`) and no span for consuming it.

After going through the code, I believe the `TraceChannelInterceptor` is the wrong inspiration for the `MessageConverterAspect`. The Interceptor detaches the Message-Span only after the message went through the Message-Handler (see `ExecutorSubscribableChannel.SendTask.run()`). This way later Interceptors or the Handler itself have access to the Span.

The `MessageConverterAspect` by comparison detaches it as soon as the `fromMessage`-Method returns, before it goes through the Message-Handler. As a result we will always loose knowledge about the Message-Span before the Message-Handler is called.

I believe a good solution would be if somewhere the Message-Span is read and continued and the `RabbitListenerAspect`/`RabbitHandlerAspect` creates and stops a child-span around the Handler-Method. Then afterwards the Message-Span is detached (like the ChannelInterceptor does it). The converter could continue the span, but it cant detach it.

**Comment by Laures** [comment]
i looked into then code for MessageListeningContainers some more and found a few decent spots for an Aspect that reads the SpanId from an Amqp message:

1) `AbstractMessageListenerContainer.invokeListener(Channel,Message)`: Probably as generic as it gets. The Listener still uses Amqp-Messages so the current `AbstractRabbitMessageReceiverAspect` should work.

2) `MessagingMessageListenerAdapter.invokeHandler(Ampq-Message,Channel,Messaging-Message)` same deal as above but the converted Messaging-Message is also available. The Tracing Headers are in both Messages.

3) HandlerAdapter.invoke(Message,Object...) As close to the actual Handler as possible. Only Messaging-Message from here on out

I will give 1) a try.

**Comment by ignacio83** [comment]
The Spring AspectJ only instrument through spring proxies. The only point who I found is in MessageConverter, unfortunately the spring-rabbit do not provided filters or interceptors to do this work better.
> From Docs: To use @AspectJ aspects in a Spring configuration you need to enable Spring support for configuring Spring AOP based on @AspectJ aspects, and autoproxying beans based on whether or not they are advised by those aspects. By autoproxying we mean that if Spring determines that a bean is advised by one or more aspects, it will automatically generate a proxy for that bean to intercept method invocations and ensure that advice is executed as needed.

**Comment by Laures** [comment]
i tried extending all my handler methods with a Messaging-Message parameter and reimplement your RabbitListener aspect using that instead of amqp-message. that worked for me.

**Comment by ignacio83** [comment]
Great, I would like to see. Could u send a PR?

**Comment by Laures** [comment]
i will try to get you a PR over the weekend.
