### ISSUE TITLE
Do not use internal Netshoes Nexus

### ISSUE THREAD

**Issue by allan-silva** [netshoes/spring-cloud-sleuth-amqp#6]
While I try to build and test the pkg, all requests to get dependencies fall into the internal netshoes nexus.

![image](https://user-images.githubusercontent.com/9947646/32579012-8b2629a6-c4c6-11e7-961f-a76610c9451f.png)

**Comment by ignacio83** [comment]
This configuration is not configured in project. Check you settings.xml
